includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/ANIL.yaml
  - backbones/resnet12.yaml


device_ids: 0
way_num: 5
shot_num: 1
query_num: 15
test_way: 5 # use ~ -> test_* = *_num
test_shot: 1
test_query: 15
episode_size: 2
train_episode: 500
test_episode: 100



# backbone:
#   name: resnet12
#   kwargs:
#     keep_prob: 0.0

# classifier:
#   name: ANIL
#   kwargs:
#     inner_param:
#       lr: 1e-3
#       iter: 10
#     feat_dim: 640


backbone:
  name: resnet18
  kwargs:

classifier:
  name: ANIL
  kwargs:
    inner_param:
      lr: 1e-3
      iter: 10
    feat_dim: 512


# backbone:
#   name: WRN
#   kwargs:
#     depth: 10
#     widen_factor: 10
#     dropRate: 0.0
#     avg_pool: True
#     is_flatten: True

# classifier:
#   name: ANIL
#   kwargs:
#     inner_param:
#       lr: 1e-3
#       iter: 10
#     feat_dim: 640
