includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  - backbones/resnet12.yaml


device_ids: 0,1
way_num: 5
shot_num: 5
query_num: 15
test_way: 5 # use ~ -> test_* = *_num
test_shot: 5
test_query: 15
episode_size: 1
train_episode: 2000
test_episode: 600

#backbone:
#  name: Conv64F
#  kwargs:
#    is_flatten: True
#    is_feature: False
#    leaky_relu: False
#    negative_slope: 0.2
#    last_pool: True

backbone:
   name: resnet12
   kwargs:
     avg_pool: true
     is_flatten : true
     keep_prob: 0.0
     maxpool_last2: true

#backbone:
# name: resnet18
#kwargs:

# backbone:
#   name: WRN
#   kwargs:
#     depth: 10
#     widen_factor: 10
#     dropRate: 0.0
#     avg_pool: True
#     is_flatten: True
